### ISSUE TITLE
[Bug]: Qwen2.5 tool calling输出格式异常，非json格式

### ISSUE THREAD

**Issue by kingfs** [QwenLM/Qwen2.5#924] opened 2024-09-19 09:07 UTC
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-72B-Instruct

### What is the scenario where the problem happened?

vllm

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

使用vllm官方docker image：`vllm/vllm-openai:v0.6.1.post2` 
启动命令： `vllm serve Qwen/Qwen2.5-72B-Instruct --enable-auto-tool-choice --tool-call-parser hermes`

### Log output

```shell
<tool_call>
{{"name": "ip_query", "arguments": {"input": "1.2.3.4"}}}
</tool_call>
```
```


### Description

#### Steps to reproduce

This happens to Qwen2.5-xB-Instruct-xxx and xxx.
The problem can be reproduced with the following steps:
1. 使用`vllm serve Qwen/Qwen2.5-72B-Instruct --enable-auto-tool-choice --tool-call-parser hermes`启动
2. 测试一个ip查询的http工具（其他也一样）
3. 输出格式不是json

#### Expected results


<tool_call>
{"name": "ip_query", "arguments": {"input": "1.2.3.4"}}
</tool_call>


其中tool_call标签内的json格式多了最外层的`{}`

#### Attempts to fix

I have tried several ways to fix this, including:
1. ...
2. ...

#### Anything else helpful for investigation

I find that this problem also happens to ...

**Comment by jklj077** [comment] 2024-09-19 09:12
duplicate of https://github.com/QwenLM/Qwen2.5/issues/918

**Comment by kingfs** [comment] 2024-09-19 09:17
另外测试了qwen2-72b，是正确输出：
```text
<tool_call>
{"name": "ip_query", "arguments": {"input": "1.2.3.4"}}
</tool_call>
```

**Closed** 2024-09-19 09:23 UTC
Labels: duplicate
